apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: npchcrlkq-go 
  janus-idp.io/tekton: npchcrlkq-go
  backstage.io/kubernetes-id: npchcrlkq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: npchcrlkq-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml